### ISSUE TITLE
pod not available in cocoapods directory

### ISSUE THREAD

**Issue by funkenstrahlen** [miche-atucha/taresip#1]
I just tried to do

```
pod 'taresip'
```
in my Podfile. But `pod install` returns `[!] Unable to find a specification for taresip`

**Comment by miche-atucha** [comment]
i was using it directly from github.
`pod 'taresip', :git => 'https://github.com/miche-atucha/taresip.git'`
i did the push to the trunk right now, so i expect be available soon.

**Comment by miche-atucha** [comment]
It is already published!

**Comment by funkenstrahlen** [comment]
Great! Thanks for your fast reply!
