### ISSUE TITLE
config: creating config template No such file or directory`

### ISSUE THREAD

**Issue by samirmagnates** [miche-atucha/taresip#12]
I had installed the Pod file, and I am getting the following error

`config: creating config template UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU/config
[31mconfig: writing UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU/config: No such file or directory`

My Code is :

      `
         guard libre_init() == 0 else { throw SipError.libre }
         
        // Initialize dynamic modules.
        mod_init()

        if let path = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).first {
             conf_path_set(path)
        }
        
        guard conf_configure() == 0 else { throw SipError.config }. //GETTING ERROR HERE...
        
        // Initialize the SIP stack.
        guard ua_init("SIP", 1, 1, 1, 0) == 0 else { throw SipError.stack }  `

could you please help me with the above error?
Thanks in advance.

**Comment by samirmagnates** [comment]
``

**Comment by miche-atucha** [comment]
Please consider other options, I'm not maintaining this project anymore.
Sorry for the inconvenience.
