### ISSUE TITLE
ua_alloc fails on real device

### ISSUE THREAD

**Issue by funkenstrahlen** [miche-atucha/taresip#5]
I use your example code in the readme to test baresip for my ios app. I run iOS 9.3.2.

When I call `ua_alloc` like this it fails:
```swift

        let addr = ["sip:XXXXXX:XXXXXXXXX@studio-link.de",
                    "transport=udp",
                    "answermode=auto",
                    "medianat=ice",
                    "stunserver=stun:XXXXXX:XXXXXXXXXX@stun.studio-link.de"
                    ]
        let addrstr = (addr.joinWithSeparator(";") as NSString).UTF8String

        // Start user agent.
        error = ua_alloc(&agent, addrstr)
        if error != 0 {
            print("error starting user agent")
            return
        }
```

It prints

```
using stunserver: 'stun:XXXXX:XXXXXXXXX@stun.studio-link.de'
XXXXXXX@studio-link.de: Using medianat `ice'
[31mua: SIP register failed: Invalid argument
```

It **does not fail in the simulator**. It only fails **on the real device**. Do you know why?

**Comment by miche-atucha** [comment]
Please try using the following as parameter for `ua_alloc`:
`let addrP: UnsafeMutablePointer<Int8> = UnsafeMutablePointer((addr.joinWithSeparator(";") as NSString).UTF8String)`
I used this as the parameter for `ua_alloc` and did worked for me. This is missing on the `README`.
Let me know if this helps.
